# Generated by Django 3.2.5 on 2021-07-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=5, max_digits=20)),
                ('pre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pre1', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
    ]
